### PR TITLE
Add font-awesome social icons

### PR DESCRIPTION
**Pull request by rafaelfranca**
Here is the example.

screen shot 2016-05-17 at 3 24 13 pm

### CODE REVIEW

**Comment by mjcoffeeholick** [comment]
Consegue separar o texto (nome da rede) do ícone? Ta muito grudado.

**Comment by rafaelfranca** [comment]
Tá bom?

screen shot 2016-05-17 at 4 07 07 pm

**Comment by mjcoffeeholick** [comment]
Fechou!

**Comment by rafaelfranca** [comment]
Rating:

screen shot 2016-05-17 at 5 01 57 pm

Olho:

screen shot 2016-05-17 at 5 02 11 pm

**Pull request merged**
